### ISSUE TITLE
Clarify wiring instructions

### ISSUE THREAD

**Issue by chicagoandy** [easybotics/esphome-ruixu-bms#1]
How are you using ground?

Your instructions say " keep the green pair connected'   

Inverter: 
Pins 4 & 5 - CAN for Battery to Inverter coms

M5Stack:
Pins 3 & 6 - paired ground
Pins 7 & 8 - RS485

Does the Inverter need the ground as well?   Everybody gets the ground?

(almost ready to attempt with my 10-rack cabinet)

**Comment by clowrey** [comment]
Yes everybody gets the ground.

-- But -- grounds are tricky and you don't want ground loops or for all the grounding current to go through the communications wires. 

To avoid this mainly make sure you have 6 AWG or 16mm2 wire between your batteries GND (not negative) case terminals and your inverter GND terminals. 

Hopefully the inverter does not connect the gnd pins on the BMS connection to the case ground but you never know..

I used shielded ethernet cables and left the green pair connected + the shield connection all the way to the inverter.

**Comment by clowrey** [comment]
Oh and if you're using one of those 1 to 2 or 3 ethernet splitters - some of them actually break out different pairs of the 8 pin input to different connectors.. I am hoping the 3 pin ones leave all the pins connected as there is no way to divide up the 4x pairs evenly between the 3 output ports.. But these are very non-standard undocumented devices. You can always cut up ethernet cables and join them in the middle to know exactly where the wires are going.

**Comment by chicagoandy** [comment]
Today I did finally get a chance to try this.     I used a 3-port cat-5 splitter.
I have 
- Ruixu - > Sol-Ark 15K using CAN using pins 3,4,5,6
- Ruixu -> ESPHome using RS485 on pins 6,7,8
- Sol-Ark -> Solar Assistant using RS485 on pins 1,2,3
