### ISSUE TITLE
Current wrong on Ruixu 48100 batteries

### ISSUE THREAD

**Issue by chicagoandy** [easybotics/esphome-ruixu-bms#2]
I'm not sure if you're interested in fixing this or not.    Please let me know what your plans are for this repo, if you're interested in supporting 48100 batteries as well.

It does appear the change you made in https://github.com/syssi/esphome-seplos-bms/commit/71e5570c135cad4d106770f6b1d8b4b43fa68d7d doesn't work for the 48100 batteries.

I have 10 of them, cell current is off by 10X due to incorrect division in that commit

![image](https://github.com/user-attachments/assets/a35690b2-6793-4119-98c5-34e71bda443b)

In this example, Battery 0 should be contributing 3.74, and the total pack current should be 38.0, not 39.    (minor discrepancy with SolarAssistant due to timing)

I'm trying to determine if any other changes are required for 48100.

**Comment by clowrey** [comment]
Sounds like an easy fix, id just make a fork and publish your own. I don't use any of the 100ah batts.

**Comment by chicagoandy** [comment]
I already have.   Thanks again.
